import 'package:flutter/material.dart';

import '../models/survey_record.dart';
import '../pages/breath_test_page.dart';
import '../pages/health_metrics_page.dart';
import '../pages/home_page.dart';
import '../pages/language_selection_page.dart';
import '../pages/mandatory_task_page.dart';
import '../pages/personal_progress_page.dart';
import '../pages/protocol_violations_page.dart';
import '../pages/risk_result_page.dart';
import '../pages/splash_page.dart';
import '../pages/survey_history_page.dart';
import '../pages/survey_page.dart';
import '../pages/survey_review_page.dart';
import '../pages/trial_info_page.dart';
import '../pages/weekly_survey_page.dart';
import 'ui_catalog_dialog_preview.dart';

class UiCatalogEntry {
  final String screenId;
  final String screenName;
  final String appLocation;
  final String captureProfile;
  final Widget Function() builder;
  final List<String> sourceFiles;
  final List<String> uiComponents;
  final List<String> translationKeys;
  final List<String> styleSources;
  final List<String> themeSources;
  final double scrollOffset;

  const UiCatalogEntry({
    required this.screenId,
    required this.screenName,
    required this.appLocation,
    required this.captureProfile,
    required this.builder,
    required this.sourceFiles,
    required this.uiComponents,
    required this.translationKeys,
    required this.styleSources,
    required this.themeSources,
    this.scrollOffset = 0,
  });
}

class UiCatalogRegistry {
  static final DateTime _seedDate = DateTime(2026, 7, 1, 10, 30);

  static List<UiCatalogEntry> entries() {
    final reviewCurrent = SurveyRecord(
      id: 'catalog_review_current',
      completedAt: _seedDate,
      type: 'weekly',
      title: 'Haftalik Kayit',
      name: 'Catalog User',
      packsPerDay: '1 paket',
      exhaleTestSeconds: 11,
      inhaleTestSeconds: 14,
      riskScore: 52,
      riskLevel: 'ORTA',
      consecutiveSmokingHabit: 'Evet',
      consecutiveSmokingCount: '2 adet',
    );
    final reviewPrevious = SurveyRecord(
      id: 'catalog_review_prev',
      completedAt: _seedDate.subtract(const Duration(days: 7)),
      type: 'weekly',
      title: 'Haftalik Kayit',
      name: 'Catalog User',
      packsPerDay: '2 paket',
      exhaleTestSeconds: 9,
      inhaleTestSeconds: 11,
      riskScore: 67,
      riskLevel: 'YUKSEK',
      consecutiveSmokingHabit: 'Evet',
      consecutiveSmokingCount: '4 adet',
    );

    return <UiCatalogEntry>[
      UiCatalogEntry(
        screenId: 'SCR-0001-SPLASH',
        screenName: 'Splash',
        appLocation: 'App start',
        captureProfile: 'baseline',
        builder: () => const SplashPage(),
        sourceFiles: const ['lib/pages/splash_page.dart'],
        uiComponents: const ['Scaffold', 'NoSmokeLogo', 'SafeArea'],
        translationKeys: const ['appName'],
        styleSources: const ['lib/pages/splash_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0002-LANGUAGE',
        screenName: 'LanguageSelection',
        appLocation: 'Onboarding -> language',
        captureProfile: 'baseline',
        builder: () => const LanguageSelectionPage(),
        sourceFiles: const ['lib/pages/language_selection_page.dart'],
        uiComponents: const ['NoSmokeLogo', 'GestureDetector', 'Container'],
        translationKeys: const ['selectLanguage', 'continue', 'otherLanguages'],
        styleSources: const ['lib/pages/language_selection_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0003-LANGUAGE-MODAL',
        screenName: 'LanguageSelectionModal',
        appLocation: 'LanguageSelection -> bottom sheet',
        captureProfile: 'baseline',
        builder: () => LanguageSelectionModal(
          selectedCode: 'en',
          onLanguageSelected: (_) {},
        ),
        sourceFiles: const ['lib/pages/language_selection_page.dart'],
        uiComponents: const [
          'DraggableScrollableSheet',
          'TextField',
          'ListTile',
        ],
        translationKeys: const [
          'searchLanguages',
          'otherLanguages',
          'backToMain',
        ],
        styleSources: const ['lib/pages/language_selection_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0004-TRIAL-INFO',
        screenName: 'TrialInfo',
        appLocation: 'Onboarding -> trial info',
        captureProfile: 'seeded',
        builder: () => const TrialInfoPage(),
        sourceFiles: const ['lib/pages/trial_info_page.dart'],
        uiComponents: const ['NoSmokeLogo', 'Card', 'FilledButton'],
        translationKeys: const [
          'trialInfoTitle',
          'trialInfoMessage',
          'continue',
        ],
        styleSources: const ['lib/pages/trial_info_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0005-SURVEY',
        screenName: 'InitialSurvey',
        appLocation: 'Onboarding -> survey',
        captureProfile: 'baseline',
        builder: () => const SurveyPage(),
        sourceFiles: const [
          'lib/pages/survey_page.dart',
          'lib/widgets/packs_per_day_section.dart',
          'lib/widgets/consecutive_smoking_section.dart',
        ],
        uiComponents: const [
          'Form',
          'DropdownButtonFormField',
          'CheckboxListTile',
        ],
        translationKeys: const [
          'initialSurvey',
          'smokingInfo',
          'lifeRoutine',
          'save',
        ],
        styleSources: const ['lib/pages/survey_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0006-BREATH-TEST',
        screenName: 'BreathTest',
        appLocation: 'Survey -> breath test',
        captureProfile: 'baseline',
        builder: () =>
            const BreathTestPage(name: 'Catalog User', packsPerDay: '1 paket'),
        sourceFiles: const ['lib/pages/breath_test_page.dart'],
        uiComponents: const ['Stopwatch', 'ElevatedButton', 'Card'],
        translationKeys: const ['breathTest', 'start', 'iBreathed'],
        styleSources: const ['lib/pages/breath_test_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0007-RISK-RESULT',
        screenName: 'RiskResult',
        appLocation: 'Breath test -> risk result',
        captureProfile: 'seeded',
        builder: () => const RiskResultPage(
          name: 'Catalog User',
          riskScore: 58,
          riskLevel: 'ORTA',
          packsPerDay: '1 paket',
          exhaleTestSeconds: 11,
          inhaleTestSeconds: 14,
        ),
        sourceFiles: const ['lib/pages/risk_result_page.dart'],
        uiComponents: const ['Card', 'ListTile', 'OutlinedButton'],
        translationKeys: const ['riskAnalysis', 'riskScore', 'taskCountToday'],
        styleSources: const ['lib/pages/risk_result_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0008-HOME',
        screenName: 'Home',
        appLocation: 'Main home dashboard',
        captureProfile: 'seeded',
        builder: () => const HomePage(
          name: 'Catalog User',
          riskScore: 58,
          riskLevel: 'ORTA',
        ),
        sourceFiles: const ['lib/pages/home_page.dart'],
        uiComponents: const ['ListView', 'Card', 'SnackBar', 'AlertDialog'],
        translationKeys: const [
          'home',
          'quickMenuTitle',
          'menuBreathTest',
          'menuWeeklySurvey',
        ],
        styleSources: const ['lib/pages/home_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0009-WEEKLY-SURVEY',
        screenName: 'WeeklySurvey',
        appLocation: 'Home -> weekly survey',
        captureProfile: 'seeded',
        builder: () => const WeeklySurveyPage(nameSeed: 'Catalog User'),
        sourceFiles: const [
          'lib/pages/weekly_survey_page.dart',
          'lib/widgets/packs_per_day_section.dart',
          'lib/widgets/consecutive_smoking_section.dart',
        ],
        uiComponents: const [
          'Slider',
          'SwitchListTile',
          'DropdownButtonFormField',
        ],
        translationKeys: const [
          'weeklySurvey',
          'weeklySavePrompt',
          'weeklyTaskCompletion',
        ],
        styleSources: const ['lib/pages/weekly_survey_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0010-MANDATORY-TASK',
        screenName: 'MandatoryTask',
        appLocation: 'Home -> mandatory task gate',
        captureProfile: 'seeded',
        builder: () =>
            const MandatoryTaskPage(taskTitle: 'ADAPTIVE_NO_SMOKE:45'),
        sourceFiles: const ['lib/pages/mandatory_task_page.dart'],
        uiComponents: const ['PopScope', 'Card', 'ElevatedButton'],
        translationKeys: const ['mandatoryTaskTitle', 'mandatoryTaskHint'],
        styleSources: const ['lib/pages/mandatory_task_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0012-PROTOCOL-VIOLATIONS',
        screenName: 'ProtocolViolations',
        appLocation: 'Home -> violation report',
        captureProfile: 'seeded',
        builder: () => const ProtocolViolationsPage(),
        sourceFiles: const ['lib/pages/protocol_violations_page.dart'],
        uiComponents: const ['ListView', 'Card', 'SummaryCard'],
        translationKeys: const ['violationReportTitle', 'violationReportEmpty'],
        styleSources: const ['lib/pages/protocol_violations_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0013-SURVEY-HISTORY',
        screenName: 'SurveyHistory',
        appLocation: 'Home -> survey history',
        captureProfile: 'seeded',
        builder: () => const SurveyHistoryPage(),
        sourceFiles: const ['lib/pages/survey_history_page.dart'],
        uiComponents: const ['FutureBuilder', 'ListView', 'ListTile'],
        translationKeys: const ['surveyHistory', 'noSurveyYet', 'unnamedUser'],
        styleSources: const ['lib/pages/survey_history_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0014-SURVEY-REVIEW',
        screenName: 'SurveyReview',
        appLocation: 'Risk result -> review',
        captureProfile: 'seeded',
        builder: () => SurveyReviewPage(
          currentRecord: reviewCurrent,
          previousRecord: reviewPrevious,
        ),
        sourceFiles: const ['lib/pages/survey_review_page.dart'],
        uiComponents: const ['Card', 'ListTile', 'ElevatedButton'],
        translationKeys: const [
          'evaluation',
          'progressPositive',
          'viewAllSurveys',
        ],
        styleSources: const ['lib/pages/survey_review_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0015-HEALTH-METRICS',
        screenName: 'HealthMetrics',
        appLocation: 'Home -> health metrics',
        captureProfile: 'seeded',
        builder: () => const HealthMetricsPage(name: 'Catalog User'),
        sourceFiles: const ['lib/pages/health_metrics_page.dart'],
        uiComponents: const [
          'FutureBuilder',
          'CircularProgressIndicator',
          'Card',
        ],
        translationKeys: const [
          'healthMetrics',
          'longitudinalAnalysis',
          'statistics',
        ],
        styleSources: const ['lib/pages/health_metrics_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0016-PERSONAL-PROGRESS',
        screenName: 'PersonalProgress',
        appLocation: 'Home -> personal progress',
        captureProfile: 'seeded',
        builder: () => const PersonalProgressPage(),
        sourceFiles: const ['lib/pages/personal_progress_page.dart'],
        uiComponents: const ['RefreshIndicator', 'CustomPaint', 'Card'],
        translationKeys: const [
          'menuPersonalProgress',
          'trendChartsTitle',
          'respFollowUpTitle',
        ],
        styleSources: const ['lib/pages/personal_progress_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0017-HOME-INCOMPLETE',
        screenName: 'HomeRegistrationIncomplete',
        appLocation: 'Home -> registration incomplete state',
        captureProfile: 'registration_incomplete',
        builder: () => const HomePage(
          name: 'Catalog User',
          riskScore: 58,
          riskLevel: 'ORTA',
        ),
        sourceFiles: const ['lib/pages/home_page.dart'],
        uiComponents: const [
          'Scaffold',
          'SingleChildScrollView',
          'ElevatedButton',
        ],
        translationKeys: const ['completeRegistration', 'welcome', 'home'],
        styleSources: const ['lib/pages/home_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0019-PROTOCOL-VIOLATIONS-EMPTY',
        screenName: 'ProtocolViolationsEmpty',
        appLocation: 'Home -> violation report -> empty state',
        captureProfile: 'empty_violations',
        builder: () => const ProtocolViolationsPage(),
        sourceFiles: const ['lib/pages/protocol_violations_page.dart'],
        uiComponents: const ['Center', 'SummaryCard', 'ListView'],
        translationKeys: const ['violationReportTitle', 'violationReportEmpty'],
        styleSources: const ['lib/pages/protocol_violations_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0020-SURVEY-HISTORY-EMPTY',
        screenName: 'SurveyHistoryEmpty',
        appLocation: 'Home -> survey history -> empty state',
        captureProfile: 'empty_history',
        builder: () => const SurveyHistoryPage(),
        sourceFiles: const ['lib/pages/survey_history_page.dart'],
        uiComponents: const ['FutureBuilder', 'Center', 'Text'],
        translationKeys: const ['surveyHistory', 'noSurveyYet'],
        styleSources: const ['lib/pages/survey_history_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0021-HEALTH-METRICS-EMPTY',
        screenName: 'HealthMetricsEmpty',
        appLocation: 'Home -> health metrics -> empty state',
        captureProfile: 'empty_metrics',
        builder: () => const HealthMetricsPage(name: 'Catalog User'),
        sourceFiles: const ['lib/pages/health_metrics_page.dart'],
        uiComponents: const ['Center', 'Text', 'CircularProgressIndicator'],
        translationKeys: const ['healthMetrics', 'noBreathTestsYet'],
        styleSources: const ['lib/pages/health_metrics_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0022-SURVEY-INITIAL-TOP',
        screenName: 'InitialSurveyTop',
        appLocation: 'Onboarding -> survey -> top section',
        captureProfile: 'baseline',
        scrollOffset: 0,
        builder: () => const SurveyPage(),
        sourceFiles: const ['lib/pages/survey_page.dart'],
        uiComponents: const ['Form', 'TextFormField', 'DropdownButton'],
        translationKeys: const ['initialSurvey', 'smokingInfo', 'name'],
        styleSources: const ['lib/pages/survey_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0023-SURVEY-INITIAL-SMOKING',
        screenName: 'InitialSurveySmokingSection',
        appLocation: 'Onboarding -> survey -> smoking questions',
        captureProfile: 'baseline',
        scrollOffset: 520,
        builder: () => const SurveyPage(),
        sourceFiles: const [
          'lib/pages/survey_page.dart',
          'lib/widgets/packs_per_day_section.dart',
          'lib/widgets/consecutive_smoking_section.dart',
        ],
        uiComponents: const ['DropdownButtonFormField', 'Card', 'Text'],
        translationKeys: const ['packOption', 'chainSmokingAsk', 'save'],
        styleSources: const ['lib/pages/survey_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0024-SURVEY-INITIAL-ROUTINE',
        screenName: 'InitialSurveyRoutineSection',
        appLocation: 'Onboarding -> survey -> routine questions',
        captureProfile: 'baseline',
        scrollOffset: 980,
        builder: () => const SurveyPage(),
        sourceFiles: const ['lib/pages/survey_page.dart'],
        uiComponents: const ['DropdownButton', 'CheckboxListTile', 'Column'],
        translationKeys: const ['lifeRoutine', 'stressLevel', 'quitReason'],
        styleSources: const ['lib/pages/survey_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0025-SURVEY-INITIAL-WORK',
        screenName: 'InitialSurveyWorkSection',
        appLocation: 'Onboarding -> survey -> work profile questions',
        captureProfile: 'baseline',
        scrollOffset: 1420,
        builder: () => const SurveyPage(),
        sourceFiles: const ['lib/pages/survey_page.dart'],
        uiComponents: const ['DropdownButton', 'Switch', 'Wrap'],
        translationKeys: const [
          'workRoutineTitle',
          'workStartLabel',
          'workEndLabel',
        ],
        styleSources: const ['lib/pages/survey_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0026-SURVEY-INITIAL-HEALTH-TRIGGERS',
        screenName: 'InitialSurveyHealthTriggersSection',
        appLocation: 'Onboarding -> survey -> health and trigger questions',
        captureProfile: 'baseline',
        scrollOffset: 1880,
        builder: () => const SurveyPage(),
        sourceFiles: const ['lib/pages/survey_page.dart'],
        uiComponents: const ['CheckboxListTile', 'ListTile', 'Form'],
        translationKeys: const ['healthStatus', 'triggers', 'asthma'],
        styleSources: const ['lib/pages/survey_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0027-WEEKLY-SURVEY-TOP',
        screenName: 'WeeklySurveyTop',
        appLocation: 'Home -> weekly survey -> top section',
        captureProfile: 'seeded',
        scrollOffset: 0,
        builder: () => const WeeklySurveyPage(nameSeed: 'Catalog User'),
        sourceFiles: const ['lib/pages/weekly_survey_page.dart'],
        uiComponents: const ['Slider', 'DropdownButtonFormField', 'Card'],
        translationKeys: const ['weeklySurvey', 'weeklyTaskCompletion'],
        styleSources: const ['lib/pages/weekly_survey_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0028-WEEKLY-SURVEY-MID',
        screenName: 'WeeklySurveyMiddle',
        appLocation: 'Home -> weekly survey -> middle section',
        captureProfile: 'seeded',
        scrollOffset: 620,
        builder: () => const WeeklySurveyPage(nameSeed: 'Catalog User'),
        sourceFiles: const ['lib/pages/weekly_survey_page.dart'],
        uiComponents: const ['Slider', 'SwitchListTile', 'Column'],
        translationKeys: const ['medication', 'support', 'motivation'],
        styleSources: const ['lib/pages/weekly_survey_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0029-WEEKLY-SURVEY-BOTTOM',
        screenName: 'WeeklySurveyBottom',
        appLocation: 'Home -> weekly survey -> bottom section',
        captureProfile: 'seeded',
        scrollOffset: 1240,
        builder: () => const WeeklySurveyPage(nameSeed: 'Catalog User'),
        sourceFiles: const ['lib/pages/weekly_survey_page.dart'],
        uiComponents: const ['TextField', 'FilledButton', 'Form'],
        translationKeys: const ['save', 'weeklySurvey', 'menuBreathTest'],
        styleSources: const ['lib/pages/weekly_survey_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0030-DIALOG-WEEKLY-MANDATORY',
        screenName: 'DialogWeeklyMandatory',
        appLocation: 'Home -> weekly mandatory dialog',
        captureProfile: 'seeded',
        builder: () => const UiCatalogAlertDialogPreview(
          titleKey: 'weeklyMandatoryTitle',
          contentKey: 'weeklyMandatoryContent',
          actionKeys: ['weeklyMandatoryGo'],
        ),
        sourceFiles: const ['lib/pages/home_page.dart'],
        uiComponents: const ['AlertDialog', 'ElevatedButton'],
        translationKeys: const [
          'weeklyMandatoryTitle',
          'weeklyMandatoryContent',
          'weeklyMandatoryGo',
        ],
        styleSources: const ['lib/pages/home_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0031-DIALOG-WEEKLY-PROMPT',
        screenName: 'DialogWeeklyPrompt',
        appLocation: 'Home -> weekly optional prompt dialog',
        captureProfile: 'seeded',
        builder: () => const UiCatalogAlertDialogPreview(
          titleKey: 'weeklySurvey',
          contentKey: 'weeklySurveyPromptAsk',
          actionKeys: ['no', 'yes'],
        ),
        sourceFiles: const ['lib/pages/home_page.dart'],
        uiComponents: const ['AlertDialog', 'TextButton', 'ElevatedButton'],
        translationKeys: const [
          'weeklySurvey',
          'weeklySurveyPromptAsk',
          'yes',
          'no',
        ],
        styleSources: const ['lib/pages/home_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0032-DIALOG-TASK-OUTCOME',
        screenName: 'DialogTaskOutcome',
        appLocation: 'Home -> task outcome dialog',
        captureProfile: 'seeded',
        builder: () => const UiCatalogAlertDialogPreview(
          titleKey: 'taskOutcomeQuestion',
          contentKey: 'taskFollowUpTitle',
          actionKeys: ['taskOutcomeNo', 'taskOutcomeYes'],
        ),
        sourceFiles: const ['lib/pages/home_page.dart'],
        uiComponents: const ['AlertDialog', 'TextButton', 'ElevatedButton'],
        translationKeys: const [
          'taskOutcomeQuestion',
          'taskOutcomeNo',
          'taskOutcomeYes',
        ],
        styleSources: const ['lib/pages/home_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0033-DIALOG-PERMISSIONS-RETRY',
        screenName: 'DialogPermissionsRetry',
        appLocation: 'Survey -> onboarding permission retry dialog',
        captureProfile: 'baseline',
        builder: () => const UiCatalogAlertDialogPreview(
          titleKey: 'permissionsRetryTitle',
          contentKey: 'permissionsRetryMessage',
          actionKeys: [
            'continueWithoutPermission',
            'openAlarmReminderSettings',
            'openSettings',
            'retry',
          ],
        ),
        sourceFiles: const ['lib/pages/survey_page.dart'],
        uiComponents: const ['AlertDialog', 'TextButton', 'FilledButton'],
        translationKeys: const [
          'permissionsRetryTitle',
          'permissionsRetryMessage',
          'continueWithoutPermission',
          'openAlarmReminderSettings',
          'openSettings',
          'retry',
        ],
        styleSources: const ['lib/pages/survey_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
      UiCatalogEntry(
        screenId: 'SCR-0034-DIALOG-BREATH-WEEKLY-PROMPT',
        screenName: 'DialogBreathWeeklyPrompt',
        appLocation: 'Breath test -> weekly prompt dialog',
        captureProfile: 'seeded',
        builder: () => const UiCatalogAlertDialogPreview(
          titleKey: 'weeklySurvey',
          contentKey: 'weeklySurveyPromptAsk',
          actionKeys: ['no', 'yes'],
        ),
        sourceFiles: const ['lib/pages/breath_test_page.dart'],
        uiComponents: const ['AlertDialog', 'TextButton', 'ElevatedButton'],
        translationKeys: const [
          'weeklySurvey',
          'weeklySurveyPromptAsk',
          'yes',
          'no',
        ],
        styleSources: const ['lib/pages/breath_test_page.dart'],
        themeSources: const ['lib/core/app_theme.dart'],
      ),
    ];
  }
}
