// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgrV2ojAw1TSms4V-V1S5f5O4FR5fbMg8',
    appId: '1:269922488535:web:e31730b896c4c3f6422092',
    messagingSenderId: '269922488535',
    projectId: 'no-smoke-7dd2e',
    authDomain: 'no-smoke-7dd2e.firebaseapp.com',
    storageBucket: 'no-smoke-7dd2e.firebasestorage.app',
    measurementId: 'G-LLWQXJ2TF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-22688NMly2DeumJH8mEDdJFfNmQ_DlM',
    appId: '1:269922488535:android:14ba91f65a04f912422092',
    messagingSenderId: '269922488535',
    projectId: 'no-smoke-7dd2e',
    storageBucket: 'no-smoke-7dd2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMBYulEqVXg7mh0ShK1mhXKeWAFQchs68',
    appId: '1:269922488535:ios:47e31614e6ce4a63422092',
    messagingSenderId: '269922488535',
    projectId: 'no-smoke-7dd2e',
    storageBucket: 'no-smoke-7dd2e.firebasestorage.app',
    iosBundleId: 'com.example.noSmoke',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMBYulEqVXg7mh0ShK1mhXKeWAFQchs68',
    appId: '1:269922488535:ios:47e31614e6ce4a63422092',
    messagingSenderId: '269922488535',
    projectId: 'no-smoke-7dd2e',
    storageBucket: 'no-smoke-7dd2e.firebasestorage.app',
    iosBundleId: 'com.example.noSmoke',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgrV2ojAw1TSms4V-V1S5f5O4FR5fbMg8',
    appId: '1:269922488535:web:61852c90a457cadb422092',
    messagingSenderId: '269922488535',
    projectId: 'no-smoke-7dd2e',
    authDomain: 'no-smoke-7dd2e.firebaseapp.com',
    storageBucket: 'no-smoke-7dd2e.firebasestorage.app',
    measurementId: 'G-GMZHE2F8PY',
  );
}
