import 'package:flutter/material.dart';

class AppTexts {
  // Turkish - Full translation
  static const Map<String, String> _tr = {
    'appName': 'NO SMOKE',
    'selectLanguage': 'Dil Sec',
    'continue': 'Devam Et',
    'yes': 'Evet',
    'no': 'Hayır',
    'save': 'Kaydet',
    'home': 'Ana Sayfa',
    'weeklySurvey': 'Haftalık Anket',
    'riskAnalysis': 'Risk Analizi',
    'retry': 'Tekrar dene',
    'start': 'Başla',
    'test': 'Test',
    'good': 'İyi',
    'bad': 'Kötü',
    'risk': 'Risk',
    'name': 'Ad',
    'age': 'Yaş',
    'gender': 'Cinsiyet',
    'male': 'Erkek',
    'female': 'Kadın',
    'selectOption': 'Seçiniz',
    'breathTest': 'Nefes Testi',
    'riskLevel': 'Risk seviyesi',
    'riskScore': 'Risk skoru',
    'initialSurvey': 'Başlangıç Anketi',
    'smokingInfo': 'Sigara Bilgileri',
    'lifeRoutine': 'Yaşam Düzeni',
    'professionLabel': 'Meslek',
    'healthStatus': 'Sağlık Durumu',
    'triggerTitle': 'Sigara Tetikleyicileri',
    'stressTitle': 'Stres Seviyesi',
    'quitReasonTitle': 'Bırakma Sebebi',
    'riskCritical': 'KRİTİK',
    'riskHigh': 'YÜKSEK',
    'riskMedium': 'ORTA',
    'riskLow': 'DÜŞÜK',
    'validationNameRequired': 'Lütfen ad alanını doldurun.',
    'validationAgeRequired': 'Lütfen yaş alanını doldurun.',
    'validationGenderRequired': 'Lütfen cinsiyet seçin.',
    'hello': 'Merhaba',
    'weeklySavePrompt': 'Bu haftaki durumunuzu kaydedin.',
    'saveErrorRetry': 'Kayıt sırasında bir hata oluştu. Lütfen tekrar deneyin.',
    'smokeFreeStreak': 'Sigara İçmeme Serisi',
    'healthMetrics': 'Sağlık Metrikleri',
    'noBreathTestsYet': 'Henüz nefes testi kaydı yok.',
    'longitudinalAnalysis': 'Zaman Serisine Dayalı Analiz',
    'statistics': 'İstatistikler',
    'recentTests': 'Son Testler',
    'exportComingSoon': 'PDF dışa aktarma yakında geliyor.',
    'exportPDF': 'PDF Olarak Dışa Aktar',
    'workDaysLabel': 'Çalıştığın günler',
    'dayMonShort': 'Pzt',
    'dayTueShort': 'Sal',
    'dayWedShort': 'Çar',
    'dayThuShort': 'Per',
    'dayFriShort': 'Cum',
    'daySatShort': 'Cmt',
    'daySunShort': 'Paz',
    'weekendPatternLabel': 'Hafta sonu içim paterni',
    'weekendPatternSame': 'Hafta içi ile aynı',
    'weekendPatternMore': 'Hafta sonu daha fazla',
    'weekendPatternLess': 'Hafta sonu daha az',
    'smokingBreakExists': 'İş yerinde sigara molası var mı?',
    'break1Start': '1. mola başlangıç',
    'break1End': '1. mola bitiş',
    'break2Exists': '2. mola var',
    'break2Start': '2. mola başlangıç',
    'break2End': '2. mola bitiş',
    'updatedWorkStart': 'Yeni mesai başlangıç saati',
    'updatedWorkEnd': 'Yeni mesai bitiş saati',
    'updatedWorkplaceRule': 'İş yerinde sigara kuralı',
    'trialInfoTitle': '14 Gunluk Ucretsiz Deneme',
    'trialInfoMessage':
      'No Smoke uygulamasini 14 gun boyunca ucretsiz deneyebilirsin. Bu surede gunluk gorevler, nefes testleri ve haftalik anketlerle birakma surecini yakindan takip edecegiz.',
  };

  // English - Full translation
  static const Map<String, String> _en = {
    'appName': 'NO SMOKE',
    'selectLanguage': 'Select language',
    'continue': 'Continue',
    'yes': 'Yes',
    'no': 'No',
    'save': 'Save',
    'home': 'Home',
    'weeklySurvey': 'Weekly Survey',
    'riskAnalysis': 'Risk Analysis',
    'retry': 'Retry',
    'start': 'Start',
    'test': 'Test',
    'good': 'Good',
    'bad': 'Bad',
    'risk': 'Risk',
    'name': 'Name',
    'age': 'Age',
    'gender': 'Gender',
    'male': 'Male',
    'female': 'Female',
    'selectOption': 'Select',
    'breathTest': 'Breath Test',
    'riskLevel': 'Risk level',
    'riskScore': 'Risk score',
    'initialSurvey': 'Initial Survey',
    'smokingInfo': 'Smoking Information',
    'lifeRoutine': 'Daily Routine',
    'professionLabel': 'Profession',
    'healthStatus': 'Health Status',
    'triggerTitle': 'Smoking Triggers',
    'stressTitle': 'Stress Level',
    'quitReasonTitle': 'Quit Reason',
    'riskCritical': 'CRITICAL',
    'riskHigh': 'HIGH',
    'riskMedium': 'MEDIUM',
    'riskLow': 'LOW',
    'validationNameRequired': 'Please fill in the name field.',
    'validationAgeRequired': 'Please fill in the age field.',
    'validationGenderRequired': 'Please select a gender.',
    'hello': 'Hello',
    'weeklySavePrompt': 'Save your status for this week.',
    'saveErrorRetry': 'An error occurred while saving. Please try again.',
    'smokeFreeStreak': 'Smoke-Free Streak',
    'healthMetrics': 'Health Metrics',
    'noBreathTestsYet': 'No breath test records yet.',
    'longitudinalAnalysis': 'Longitudinal Analysis',
    'statistics': 'Statistics',
    'recentTests': 'Recent Tests',
    'exportComingSoon': 'PDF export coming soon.',
    'exportPDF': 'Export as PDF',
    'workDaysLabel': 'Working days',
    'dayMonShort': 'Mon',
    'dayTueShort': 'Tue',
    'dayWedShort': 'Wed',
    'dayThuShort': 'Thu',
    'dayFriShort': 'Fri',
    'daySatShort': 'Sat',
    'daySunShort': 'Sun',
    'weekendPatternLabel': 'Weekend smoking pattern',
    'weekendPatternSame': 'Same as weekdays',
    'weekendPatternMore': 'More on weekends',
    'weekendPatternLess': 'Less on weekends',
    'smokingBreakExists': 'Are smoking breaks available at work?',
    'break1Start': 'Break 1 start',
    'break1End': 'Break 1 end',
    'break2Exists': 'Second break available',
    'break2Start': 'Break 2 start',
    'break2End': 'Break 2 end',
    'updatedWorkStart': 'Updated work start time',
    'updatedWorkEnd': 'Updated work end time',
    'updatedWorkplaceRule': 'Workplace smoking rule',
    'trialInfoTitle': '14-Day Free Trial',
    'trialInfoMessage':
      'You can use No Smoke free for 14 days. During this period, we guide your quit journey with daily tasks, breath tests, and weekly surveys.',
  };

  // All 40 languages - each inherits from EN, with top keys translated
  static final Map<String, Map<String, String>> _data = {
    'tr': _tr,
    'en': _en,
    // German
    'de': {
      ..._en,
      'selectLanguage': 'Sprache wählen',
      'appName': 'NICHT RAUCHEN',
      'initialSurvey': 'Anfangsumfrage',
      'continue': 'Weiter',
      'yes': 'Ja',
      'no': 'Nein',
      'home': 'Startseite',
      'weeklySurvey': 'Wöchentliche Umfrage',
      'riskAnalysis': 'Risikoanalyse',
      'save': 'Speichern',
      'retry': 'Erneut versuchen',
      'start': 'Starten',
      'name': 'Name',
      'age': 'Alter',
      'gender': 'Geschlecht',
      'male': 'Männlich',
      'female': 'Weiblich',
    },
    // Arabic
    'ar': {
      ..._en,
      'selectLanguage': 'اختر اللغة',
      'appName': 'لا تدخن',
      'initialSurvey': 'الاستطلاع الأولي',
      'continue': 'تابع',
      'yes': 'نعم',
      'no': 'لا',
      'home': 'الرئيسية',
      'weeklySurvey': 'المسح الأسبوعي',
      'save': 'حفظ',
      'start': 'ابدأ',
      'name': 'الاسم',
    },
    // French
    'fr': {
      ..._en,
      'selectLanguage': 'Choisir la langue',
      'appName': 'ARRÊT DU TABAC',
      'initialSurvey': 'Enquête initiale',
      'continue': 'Continuer',
      'yes': 'Oui',
      'no': 'Non',
      'home': 'Accueil',
      'weeklySurvey': 'Enquête hebdomadaire',
      'save': 'Enregistrer',
      'start': 'Démarrer',
      'name': 'Nom',
    },
    // Spanish
    'es': {
      ..._en,
      'selectLanguage': 'Seleccionar idioma',
      'appName': 'SIN HUMO',
      'initialSurvey': 'Encuesta inicial',
      'continue': 'Continuar',
      'yes': 'Sí',
      'no': 'No',
      'home': 'Inicio',
      'weeklySurvey': 'Encuesta semanal',
      'save': 'Guardar',
      'start': 'Comenzar',
      'name': 'Nombre',
    },
    // Portuguese
    'pt': {
      ..._en,
      'selectLanguage': 'Selecione o idioma',
      'appName': 'SEM FUMO',
      'continue': 'Continuar',
      'yes': 'Sim',
      'no': 'Não',
      'home': 'Início',
      'save': 'Salvar',
      'start': 'Começar',
      'name': 'Nome',
    },
    // Italian
    'it': {
      ..._en,
      'selectLanguage': 'Seleziona lingua',
      'appName': 'SENZA FUMO',
      'continue': 'Continua',
      'yes': 'Sì',
      'no': 'No',
      'home': 'Home',
      'save': 'Salva',
      'start': 'Inizia',
      'name': 'Nome',
    },
    // Polish
    'pl': {
      ..._en,
      'selectLanguage': 'Wybierz język',
      'appName': 'BEZ DYMU',
      'continue': 'Dalej',
      'yes': 'Tak',
      'no': 'Nie',
      'home': 'Strona główna',
      'save': 'Zapisz',
      'start': 'Rozpocznij',
      'name': 'Imię',
    },
    // Russian
    'ru': {
      ..._en,
      'selectLanguage': 'Выберите язык',
      'appName': 'БЕЗ ДЫМА',
      'continue': 'Продолжить',
      'yes': 'Да',
      'no': 'Нет',
      'home': 'Главная',
      'save': 'Сохранить',
      'start': 'Начать',
      'name': 'Имя',
    },
    // Japanese
    'ja': {
      ..._en,
      'selectLanguage': '言語を選択',
      'appName': '禁煙',
      'continue': '続行',
      'yes': 'はい',
      'no': 'いいえ',
      'home': 'ホーム',
      'save': '保存',
      'start': '開始',
      'name': '名前',
    },
    // Chinese
    'zh': {
      ..._en,
      'selectLanguage': '选择语言',
      'appName': '无烟',
      'continue': '继续',
      'yes': '是',
      'no': '否',
      'home': '首页',
      'save': '保存',
      'start': '开始',
      'name': '名字',
    },
    // Korean
    'ko': {
      ..._en,
      'selectLanguage': '언어 선택',
      'appName': '금연',
      'continue': '계속',
      'yes': '예',
      'no': '아니오',
      'home': '홈',
      'save': '저장',
      'start': '시작',
      'name': '이름',
    },
    // Hindi
    'hi': {
      ..._en,
      'selectLanguage': 'भाषा चुनें',
      'appName': 'धुआं नहीं',
      'continue': 'जारी रखें',
      'yes': 'हाँ',
      'no': 'नहीं',
      'home': 'होम',
      'save': 'सहेजें',
      'start': 'शुरु करें',
      'name': 'नाम',
    },
    // Thai
    'th': {
      ..._en,
      'selectLanguage': 'เลือกภาษา',
      'appName': 'ไม่สูบบุหรี่',
      'continue': 'ต่อไป',
      'yes': 'ใช่',
      'no': 'ไม่ใช่',
      'home': 'หน้าแรก',
      'save': 'บันทึก',
      'start': 'เริ่ม',
      'name': 'ชื่อ',
    },
    // Vietnamese
    'vi': {
      ..._en,
      'selectLanguage': 'Chọn ngôn ngữ',
      'appName': 'KHÔNG HÚT THUỐC',
      'continue': 'Tiếp tục',
      'yes': 'Có',
      'no': 'Không',
      'home': 'Trang chủ',
      'save': 'Lưu',
      'start': 'Bắt đầu',
      'name': 'Tên',
    },
    // Indonesian
    'id': {
      ..._en,
      'selectLanguage': 'Pilih bahasa',
      'appName': 'BEBAS ASAP',
      'continue': 'Lanjutkan',
      'yes': 'Ya',
      'no': 'Tidak',
      'home': 'Beranda',
      'save': 'Simpan',
      'start': 'Mulai',
      'name': 'Nama',
    },
    // Bengali
    'bn': {
      ..._en,
      'selectLanguage': 'ভাষা নির্বাচন করুন',
      'continue': 'চালিয়ে যান',
      'yes': 'হাঁ',
      'no': 'না',
      'home': 'হোম',
      'save': 'সংরক্ষণ করুন',
      'start': 'শুরু করুন',
    },
    // Punjabi
    'pa': {
      ..._en,
      'selectLanguage': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      'continue': 'ਜਾਰੀ ਰੱਖੋ',
      'yes': 'ਹਾਂ',
      'no': 'ਨਹੀਂ',
      'home': 'ਹੋਮ',
      'save': 'ਸੰਭਾਲੋ',
      'start': 'ਸ਼ੁਰੂ ਕਰੋ',
    },
    // Telugu
    'te': {
      ..._en,
      'selectLanguage': 'భాషను ఎంచుకోండి',
      'continue': 'కొనసాగించు',
      'yes': 'అవును',
      'no': 'కాదు',
      'home': 'హోమ్',
      'save': 'సేవ్ చేయండి',
      'start': 'ప్రారంభించండి',
    },
    // Tamil
    'ta': {
      ..._en,
      'selectLanguage': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'continue': 'தொடரவும்',
      'yes': 'ஆம்',
      'no': 'இல்லை',
      'home': 'வீடு',
      'save': 'சேமிக்கவும்',
      'start': 'தொடங்கவும்',
    },
    // Malayalam
    'ml': {
      ..._en,
      'selectLanguage': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'continue': 'തുടരുക',
      'yes': 'അതെ',
      'no': 'ഇല്ല',
      'home': 'ഹോം',
      'save': 'സംരക്ഷിക്കുക',
      'start': 'തുടങ്ങുക',
    },
    // Gujarati
    'gu': {
      ..._en,
      'selectLanguage': 'ભાષા પસંદ કરો',
      'continue': 'આગળ વધો',
      'yes': 'હા',
      'no': 'ના',
      'home': 'હોમ',
      'save': 'સંગ્રહો',
      'start': 'શરુ કરો',
    },
    // Kannada
    'kn': {
      ..._en,
      'selectLanguage': 'ಭಾಷೆ ಆರಿಸಿ',
      'continue': 'ಮುಂದುವರಿಸಿ',
      'yes': 'ಹೌದು',
      'no': 'ಇಲ್ಲ',
      'home': 'ಮುಖಪುಟ',
      'save': 'ಉಳಿಸಿ',
      'start': 'ಪ್ರಾರಂಭಿಸಿ',
    },
    // Marathi
    'mr': {
      ..._en,
      'selectLanguage': 'भाषा निवडा',
      'continue': 'चालू ठेवा',
      'yes': 'होय',
      'no': 'नाही',
      'home': 'मुखपृष्ठ',
      'save': 'जतन करा',
      'start': 'सुरू करा',
    },
    // Ukrainian
    'uk': {
      ..._en,
      'selectLanguage': 'Виберіть мову',
      'appName': 'БЕЗ ДИМУ',
      'continue': 'Продовжити',
      'yes': 'Так',
      'no': 'Ні',
      'home': 'Головна',
      'save': 'Зберегти',
      'start': 'Почати',
    },
    // Romanian
    'ro': {
      ..._en,
      'selectLanguage': 'Alegeți limba',
      'continue': 'Continuă',
      'yes': 'Da',
      'no': 'Nu',
      'home': 'Acasă',
      'save': 'Salvează',
      'start': 'Început',
    },
    // Greek
    'el': {
      ..._en,
      'selectLanguage': 'Επιλέξτε γλώσσα',
      'continue': 'Συνέχεια',
      'yes': 'Ναι',
      'no': 'Όχι',
      'home': 'Αρχική',
      'save': 'Αποθήκευση',
      'start': 'Εκκίνηση',
    },
    // Hungarian
    'hu': {
      ..._en,
      'selectLanguage': 'Válassza ki a nyelvet',
      'continue': 'Folytatás',
      'yes': 'Igen',
      'no': 'Nem',
      'home': 'Kezdőlap',
      'save': 'Mentés',
      'start': 'Indítás',
    },
    // Czech
    'cs': {
      ..._en,
      'selectLanguage': 'Vyberte jazyk',
      'continue': 'Pokračovat',
      'yes': 'Ano',
      'no': 'Ne',
      'home': 'Domů',
      'save': 'Uložit',
      'start': 'Začít',
    },
    // Swedish
    'sv': {
      ..._en,
      'selectLanguage': 'Välj språk',
      'appName': 'RÖKFRI',
      'continue': 'Fortsätt',
      'yes': 'Ja',
      'no': 'Nej',
      'home': 'Hem',
      'save': 'Spara',
      'start': 'Börja',
    },
    // Danish
    'da': {
      ..._en,
      'selectLanguage': 'Vælg sprog',
      'continue': 'Fortsæt',
      'yes': 'Ja',
      'no': 'Nej',
      'home': 'Hjem',
      'save': 'Gem',
      'start': 'Start',
    },
    // Norwegian
    'no': {
      ..._en,
      'selectLanguage': 'Velg språk',
      'appName': 'RØYKFRI',
      'continue': 'Fortsett',
      'yes': 'Ja',
      'no': 'Nei',
      'home': 'Hjem',
      'save': 'Lagre',
      'start': 'Start',
    },
    // Finnish
    'fi': {
      ..._en,
      'selectLanguage': 'Valitse kieli',
      'appName': 'SAVUTON',
      'continue': 'Jatka',
      'yes': 'Kyllä',
      'no': 'Ei',
      'home': 'Koti',
      'save': 'Tallenna',
      'start': 'Aloita',
    },
    // Dutch
    'nl': {
      ..._en,
      'selectLanguage': 'Selecteer taal',
      'continue': 'Doorgaan',
      'yes': 'Ja',
      'no': 'Nee',
      'home': 'Start',
      'save': 'Opslaan',
      'start': 'Begin',
    },
    // Belarusian
    'be': {
      ..._en,
      'selectLanguage': 'Выберыце мову',
      'appName': 'БЕЗ ДЫМУ',
      'continue': 'Прадолжыць',
      'yes': 'Так',
      'no': 'Не',
      'home': 'Галоўная',
      'save': 'Сахаваць',
      'start': 'Пачаць',
    },
    // Serbian
    'sr': {
      ..._en,
      'selectLanguage': 'Izaberite jezik',
      'continue': 'Nastavi',
      'yes': 'Da',
      'no': 'Ne',
      'home': 'Početna',
      'save': 'Spremi',
      'start': 'Počni',
    },
    // Croatian
    'hr': {
      ..._en,
      'selectLanguage': 'Odaberite jezik',
      'continue': 'Nastavi',
      'yes': 'Da',
      'no': 'Ne',
      'home': 'Početna',
      'save': 'Spremi',
      'start': 'Počni',
    },
    // Malay
    'ms': {
      ..._en,
      'selectLanguage': 'Pilih bahasa',
      'continue': 'Lanjutkan',
      'yes': 'Ya',
      'no': 'Tidak',
      'home': 'Beranda',
      'save': 'Simpan',
      'start': 'Mulai',
    },
    // Filipino
    'fil': {
      ..._en,
      'selectLanguage': 'Piliin ang wika',
      'continue': 'Magpatuloy',
      'yes': 'Oo',
      'no': 'Hindi',
      'home': 'Tahanan',
      'save': 'I-save',
      'start': 'Magsimula',
    },
  };

  static String text(BuildContext context, String key) {
    final code = Localizations.localeOf(context).languageCode;
    final langMap = _data[code] ?? _data['en']!;
    return langMap[key] ?? _data['en']![key] ?? _data['tr']![key] ?? key;
  }
}

extension AppTextsX on BuildContext {
  String t(String key) => AppTexts.text(this, key);
}
